import rawKucherenko from "../../goldens/v0.9.1/kucherenko.json";
import rawMorris from "../../goldens/v0.9.1/morris.json";
import rawPce from "../../goldens/v0.9.1/pce.json";
import rawShapley from "../../goldens/v0.9.1/shapley.json";
import rawSobol from "../../goldens/v0.9.1/sobol.json";

export interface Golden {
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[]; variance: number[] };
  tolerance: { rtol: number; atol: number };
}

interface RawGolden {
  method: string;
  n: number;
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[]; variance: number | number[] };
  tolerance: { rtol: number; atol: number };
}

// SAFETY: the imported JSON fixture is generated by goldens/generate.py with this schema.
const RAW = rawKucherenko as RawGolden;

export function loadKucherenkoGolden(): Golden {
  const variance = RAW.expected.variance;

  return {
    x: RAW.x,
    y: RAW.y,
    expected: {
      S1: RAW.expected.S1,
      ST: RAW.expected.ST,
      // The fixture stores the single variance as a bare float, not a
      // one-element list; normalize it so consumers always see number[].
      variance: Array.isArray(variance) ? variance : [variance],
    },
    tolerance: RAW.tolerance,
  };
}

export interface SobolGolden {
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[] };
  tolerance: { rtol: number; atol: number };
  config: { baseN: number; calcSecondOrder: boolean };
}

interface RawSobolGolden {
  method: string;
  n: number;
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[] };
  tolerance: { rtol: number; atol: number };
  config: { base_n: number; calc_second_order: boolean };
}

// SAFETY: the imported JSON fixture is generated by goldens/generate.py with this schema.
const RAW_SOBOL = rawSobol as RawSobolGolden;

export function loadSobolGolden(): SobolGolden {
  return {
    x: RAW_SOBOL.x,
    y: RAW_SOBOL.y,
    expected: RAW_SOBOL.expected,
    tolerance: RAW_SOBOL.tolerance,
    config: {
      baseN: RAW_SOBOL.config.base_n,
      calcSecondOrder: RAW_SOBOL.config.calc_second_order,
    },
  };
}

export interface MorrisGoldenDesign {
  n_expanded: number;
  n_trajectories: number;
  num_levels: number;
  expanded_to_unique: number[];
  ee_idx_after: number[][];
  ee_idx_before: number[][];
  ee_delta: number[][];
}

export interface MorrisGolden {
  x: number[][];
  y: number[];
  expected: { mu: number[]; mu_star: number[]; sigma: number[] };
  tolerance: { rtol: number; atol: number };
  design: MorrisGoldenDesign;
}

interface RawMorrisGolden {
  method: string;
  n: number;
  x: number[][];
  y: number[];
  expected: { mu: number[]; mu_star: number[]; sigma: number[] };
  tolerance: { rtol: number; atol: number };
  design: MorrisGoldenDesign;
}

// SAFETY: the imported JSON fixture is generated by goldens/generate.py with this schema.
const RAW_MORRIS = rawMorris as RawMorrisGolden;

export function loadMorrisGolden(): MorrisGolden {
  return {
    x: RAW_MORRIS.x,
    y: RAW_MORRIS.y,
    expected: RAW_MORRIS.expected,
    tolerance: RAW_MORRIS.tolerance,
    design: RAW_MORRIS.design,
  };
}

export interface PceGolden {
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[] };
  tolerance: { rtol: number; atol: number };
  config: { order: number; ridge: number };
}

interface RawPceGolden {
  method: string;
  n: number;
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[] };
  tolerance: { rtol: number; atol: number };
  config: { order: number; ridge: number; n: number; seed: number };
}

// SAFETY: the imported JSON fixture is generated by goldens/generate.py with this schema.
const RAW_PCE = rawPce as RawPceGolden;

export function loadPceGolden(): PceGolden {
  return {
    x: RAW_PCE.x,
    y: RAW_PCE.y,
    expected: RAW_PCE.expected,
    tolerance: RAW_PCE.tolerance,
    config: { order: RAW_PCE.config.order, ridge: RAW_PCE.config.ridge },
  };
}

export interface ShapleyGolden {
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[]; Sh: number[] };
  tolerance: { rtol: number; atol: number };
  config: { backend: string; order: number };
}

interface RawShapleyGolden {
  method: string;
  n: number;
  x: number[][];
  y: number[];
  expected: { S1: number[]; ST: number[]; Sh: number[] };
  tolerance: { rtol: number; atol: number };
  config: { backend: string; order: number; n: number; seed: number };
}

// SAFETY: the imported JSON fixture is generated by goldens/generate.py with this schema.
const RAW_SHAPLEY = rawShapley as RawShapleyGolden;

export function loadShapleyGolden(): ShapleyGolden {
  return {
    x: RAW_SHAPLEY.x,
    y: RAW_SHAPLEY.y,
    expected: RAW_SHAPLEY.expected,
    tolerance: RAW_SHAPLEY.tolerance,
    config: { backend: RAW_SHAPLEY.config.backend, order: RAW_SHAPLEY.config.order },
  };
}
